### PR TITLE
Polish Update v2

### PR DESCRIPTION
**Pull request by RealOrondil**
Hopefully this works.
Updated the Polish translation.

### CODE REVIEW

**Comment by WinstonSung** [comment]
**Merge conflict:**
You need to rebase these commits.

**Easiest way:**
Delete your forked repository and re-fork it, then re-add these translations (by upload, online editing, etc.).

**Advanced way:**
Force-push your forked repository to the latest master commit, then fix the conflicts or re-commit them.

CC:
@RealOrondil

**Comment by RealOrondil** [comment]
Okay, I have no idea of what any of that means :D
I'm not sure I fixed it, although "This branch has no conflicts with the base branch" looks like it's all good now.

**Comment by WinstonSung** [comment]
Yeah, it resolved the merge conflict.

**Comment by WinstonSung** [comment]
(The only thing I'm not sure is the warnings seems to be cleaned up before, I'm not sure whether to keep those.)

**Comment by arnog** [comment]
Thanks for the update!

**Pull request merged**
