### PR TITLE
Minor fixes to the Hungarian localization

### PR DESCRIPTION
**Pull request by krmarci**
~~I could NOT yet solve the "gy" problem: https://github.com/arnog/tecendil-js/issues/66~~

### CODE REVIEW

**Comment by krmarci** [comment]
**A temporary (?) fix to the "gy" problem - "gy" now spelled correctly, with some potentially broken traditional orthographies**

In the previous version, the "gy" letter combination was broken (it should have been ando + double dot below, which it wasn't). In this new version, I solve the problem by preprocessing gy to dy, and then using y as the double dot below character in all cases.

However, this has the problem that many Hungarian names have traditional orthographies that use y for the sound [i]. As a result, e.g. Ady (a famous poet, pronounced [ɒdi]) is spelled the same as "agy" (meaning brain, pronounced [ɒɟ]), apart from the capitalisation. This could be a good thing or a bad thing, but I'm not sure which.

**Comment by krmarci** [comment]
I solved the problem with the double-letters by removing the preprocessings (with the exception of gy to dy). I might add a dictionary with special orthographies, but so far, I would say that the current version is better than the original one.

**Review by arnog — COMMENTED** [review]
Keeping in mind that I don't speak Hungarian, I have the following questions:
- should `"ggy": "ddy"` and `"gy": "dy"` really be a pre-process rule, or should they just be regular rules.
- Removing the other pre-process rules is fine, but shouldn't they be replaced with equivalent rules, for example for `"ly": "ľ`, shouldn't there be a rule for `"ly": "[double-dot-below]{lambe}"`, etc...? Otherwise it seems that some cases that were handled before won't work now.
- Similarly, shouldn't all the rules you've removed that contained a "ť", etc...  be kept? 
- Are you sure that all the `y$` are transcribed the same way, regardless of the vowel before? That seems strange.

**Comment by krmarci** [comment]
In this version, the palatal consonants are solved by changing the y to a double dot below. But yes, I could make separate rules for gy, ggy, ly, lly, ny, nny, ty and tty without preprocessing.

About the final y: it only appears in names with traditional orthographies: Görgey, Horthy, Márki-Zay, Medgyessy, Rhédey, Vécsey, etc. It can have be pronounced either [i] or [j], depending on the name. I'm a bit unsure on how to handle it. One of the sources simply converts it to i, the other uses inverted triple dot above for [i] and anna with double dot below for [j]. Someone on Reddit (https://www.reddit.com/r/Tengwar/comments/xv6r0v/comment/ir5zepe/?utm_source=reddit&utm_medium=web2x&context=3) suggested using double dot above for ü, double acute for ö and using the breve for y. My solution uses this telco with double dot below solution, which might not be ideal.

**Comment by arnog** [comment]
Thanks! I've updated Tecendil with those changes.

**Pull request merged**
