### PR TITLE
Add German orthographic mode

### PR DESCRIPTION
**Pull request by alexander-koerschgen**
Added new mode file for a German orthographic mode.

Some improvements are planned (see comments in mode file). If this is included in Tecendil, it would be great to have it linked to German wikipedia for additional testing.

### CODE REVIEW

**Comment by arnog** [comment]
Looks good to me. Thanks for your contribution!

**Comment by arnog** [comment]
Tecendil has been updated with the mode file. And the Wikipedia articles will use the German Wikipedia when the mode is set to German.

**Comment by alexander-koerschgen** [comment]
Thanks, much appreciated!

I noticed one little oddity with the German Wikipedia integration: Umlauts seem to be normalized somehow, i.e., ä -> a, ö -> o, ü -> u. This is only true for the Wikipedia article transcription, not for the transcription in the first box.

Example with the word "Gültigkeit": ü is transcribed correctly in the top box, but the Wikipedia article headline (in red) says "Gultigkeit".
image

Still, the Wikipedia transcription is legible and very helpful for improving this mode.

**Comment by arnog** [comment]
Thanks for letting me know. This should now be fixed.

**Pull request merged**
